### ISSUE TITLE
error request 

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#17]
![bugs](https://puu.sh/EaSyu/d3381df858.gif)

this bug appear on 2019-08 and its a critical bug cause player must return menu to do future operator.

- [x] recheck if its still happen.
- [ ] found reason and fix

**Comment by Babygogogo** [comment]
This bug should have been fixed some months ago. Please reopen this issue if it happens again.

**Comment by RushFTK** [comment]
![2019-11-05_09-20-54](https://user-images.githubusercontent.com/20500319/68171181-b9044280-ffad-11e9-92b6-1fe9538428ef.gif)
Rechecked done, it still happen

**Comment by RushFTK** [comment]
it have been fixed on above update.
